update defendee set imgdist = "http://13.209.109.159:3001/images/netflix/rumors.jpg" where name like "13%";
update defendee set imgdist = "http://13.209.109.159:3001/images/netflix/lovedeath.jpg" where name like "LOVE%";
update defendee set imgdist = "http://13.209.109.159:3001/images/netflix/orange.jpg" where name like "Orange%";
update defendee set imgdist = "http://13.209.109.159:3001/images/netflix/stranger.jpg" where name like "기묘한%";
update defendee set imgdist = "http://13.209.109.159:3001/images/netflix/walking.jpg" where name like "The%";
update defendee set imgdist = "http://13.209.109.159:3001/images/netflix/breaking.jpg" where name like "Breaking%";
update defendee set imgdist = "http://13.209.109.159:3001/images/netflix/good.jpg" where name like "왕좌%";
update defendee set imgdist = "http://13.209.109.159:3001/images/netflix/frozen.jpg" where name like "Black%";

update defendee set detailed = "Illegal link and download file" where name like "13%";
update defendee set detailed = "Illegal link and download file" where name like "LOVE%";
update defendee set detailed = "Illegal link and download file" where name like "Orange%";
update defendee set detailed = "Illegal link and download file" where name like "기묘한%";
update defendee set detailed = "Illegal link and download file" where name like "The%";
update defendee set detailed = "Illegal link and download file" where name like "Breaking%";
update defendee set detailed = "Illegal link and download file" where name like "왕좌%";
update defendee set detailed = "Illegal link and download file" where name like "Black%";

update copyrighter set logo = 3 where name = "Watcha";
update copyrighter set logo = 0 where name = "Disney";
update copyrighter set logo = 1 where name = "Netflix";
update copyrighter set logo = 5 where name = "Bts";
update copyrighter set logo = 3 where name = "Tving";
update copyrighter set logo = 5 where name = "Hulu";
update copyrighter set logo = 4 where name = "Imagine Dragons";
update copyrighter set logo = 2 where name = "Naver";
update copyrighter set logo = 1 where name = "wavve";

update defendee set imgdist = "http://13.209.109.159:3001/images/The.jpg" where name like "The Game%";
update defendee set imgdist = "http://13.209.109.159:3001/images/btson.jpg" where name like "Bts%";
update defendee set imgdist = "http://13.209.109.159:3001/images/Fro.jpg" where name like "Fro%";
update defendee set imgdist = "http://13.209.109.159:3001/images/Its.jpg" where name like "Its%";
update defendee set imgdist = "http://13.209.109.159:3001/images/face.png" where name like "Appearanceism%";
update defendee set imgdist = "http://13.209.109.159:3001/images/radioactive.jpeg" where name like "Ra%";
update defendee set imgdist = "http://13.209.109.159:3001/images/yourturn.jpeg" where name like "It's your turn%";
update defendee set imgdist = "http://13.209.109.159:3001/images/stranger.jpg" where name like "Strange%";
update defendee set imgdist = "http://13.209.109.159:3001/images/believer.jpeg" where name like "Believer%";
update defendee set imgdist = "http://13.209.109.159:3001/images/zoo.jpg" where name like "Zootopia%";
update defendee set imgdist = "http://13.209.109.159:3001/images/sam.jpg" where name like "Three%";
update defendee set detailed = "Illegal link and download file" where name like "The%";
update defendee set detailed = 'Illegal link and download file' where name like "Bts%";
update defendee set detailed = "Unlicensed link about Frozen" where name like "Fro%";
update defendee set detailed = "Illegal link and download file" where name like "Its%";
update defendee set detailed = "Presubcribe not in naver" where name like "Appearanceism%";
update defendee set detailed = "Report for Plagiarism" where name like "Ra%";
update defendee set detailed = "Illegal link and download file" where name like "It's your turn%";
update defendee set detailed = "Unlicensed link about Stranger Things" where name like "Strang%";
update defendee set detailed = "Unlicensed streaming or download page" where name like "Believer%";
update defendee set detailed = "Illegal video about zootopia" where name like "Zootopia%";
update defendee set detailed = "Illegal broadcast that is not from Tving" where name like "Three%";
select * from defendee;
commit;

